artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_url: https://github.com/Sumukhagc/datasets/raw/main/twitter_training.zip
    local_dir: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion  